### ISSUE TITLE
Some bosses don't die anymore

### ISSUE THREAD

**Issue by cheetahsbdf** [NemesisSSBU/Playable_Bosses#43] opened 2023-07-30 16:37 UTC
Bosses like Master Hand and Crazy Hand tend to not die when they are killed. They usually end up "dead" but still in game and moving around. Their particle and death animation don't play. Could this please be fixed?

**Comment by NemesisSSBU** [comment] 2023-07-30 18:33
Thank you for reporting the issues. After playing all the bosses and against them, I haven’t encountered an instance where the player or CPU is able to still move around as the boss or the actual invisible Mario character that all bosses have. Also the particle and death animation not playing would be linked to this issue. If you can, can you take a screen capture of when this happens? My guess is it’s when a status change is forced at the same time the death animation is but that’s just a guess since I did change some death code a few updates before.

**Comment by cheetahsbdf** [comment] 2023-07-31 02:48
No problem. Yeah I seem to have made a mistake, they don't move, yet their death animation never plays and they reset to 0%.

**Comment by NemesisSSBU** [comment] 2023-07-31 04:50
I haven’t encountered the issue where there Death animation doesn’t play, is there a specific sequence that results in this happening?

**Comment by cheetahsbdf** [comment] 2023-07-31 16:31
Seems to me that at first it doesn't. after a few seconds, it does play. If I fight a singular boss, I have had moments where the boss doesn't die faster than the Game ending.

**Comment by NemesisSSBU** [comment] 2023-07-31 18:56
Oh is this happening only during stamina mode? The game has trouble instantly reading the instant the player dies at 0 HP.

**Comment by NemesisSSBU** [comment] 2023-07-31 21:31
I just did some adjustments to the bosses in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0) as well as uploaded its source code in case you want to fiddle with it.

**Comment by NemesisSSBU** [comment] 2023-08-01 07:43
Please reopen the issue if this problem persists in the latest build

**Comment by NemesisSSBU** [comment] 2023-08-03 00:04
Good news, I actually was able to replicate this issue and it was caused by the game ending at the same time the boss dies. This next update is going to overhaul the way bosses die and this will fix the issue.

**Comment by NemesisSSBU** [comment] 2023-08-03 00:32
Finally fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)!

**Closed by NemesisSSBU** 2023-08-03 00:32 UTC
Labels: bug, 💫 Fixed 💫
