### ISSUE TITLE
Dracula and the final bosses still crash the game

### ISSUE THREAD

**Issue by MetalGearPearl** [NemesisSSBU/Playable_Bosses#14] opened 2023-06-22 02:20 UTC
Hi there, I have downloaded the latest version of the mod and the problem with Dracula, Galeem and Darkhon persists, I deleted some folders that I had and anyway the game keeps freezing on the Vs screen
And WoL Master Hand spawns as Mario

Oh and btw, Dracula has the Mario logo instead of Castlevania 🦇

**Comment by NemesisSSBU** [comment] 2023-06-22 03:18
I was able to replicate this problem on the Ryujinx emulator but not on the actual Switch console. This could possibly be an issue on Ryujinxs' end but I'm going to run a few more tests and see if I can replicate this on console.

Are you playing on an emulator or console?

**Comment by MetalGearPearl** [comment] 2023-06-22 03:23
Console, with Atmosphere

**Comment by NemesisSSBU** [comment] 2023-06-22 03:36
I was able to replicate the issue on console by using an outdated version of Skyline.

This is most likely the issue on your end as well and I just uploaded a new version in the [same release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.8.2) to contain an updated version of Skyline (this is what's inside the exefs folder, you can pretty much ignore the actual mod file. Drag and drop in the new main.npdm and subsdk9 files into your exefs folder). The only difference with the actual mod itself in this new update would be that I changed Dracula's logo to Castlevania and changed Dracula's way of spawning in to how he originally was (wouldn't effect much).

**Comment by MetalGearPearl** [comment] 2023-06-22 03:38
Thanks a lot, I'll check it out

**Comment by MetalGearPearl** [comment] 2023-06-22 04:15
I have bad news... Those 3 bosses still do not work :/

**Comment by NemesisSSBU** [comment] 2023-06-22 05:08
Very strange. Is there any potential conflicting ARCropolis mods installed? If not, could you walk through what happens when selecting those characters? Is there an item sound effect playing or a glimpse of gameplay or is it just straight to a crash?

**Comment by MetalGearPearl** [comment] 2023-06-22 16:46
Hmm, I don't think I've done that, I'll try to update it and see if that fixes it

**Comment by MetalGearPearl** [comment] 2023-06-22 18:36
After updating Atmosphere and even the Firmware to the latest, the problem remains :/
Oh, and I also found another bug, if Master Hand or Marx use their black hole attack, the fighter in it will become invisible and in the results screen it will become totally black

**Comment by NemesisSSBU** [comment] 2023-06-22 21:49
I’ve tried for the past couple of hours to replicate this issue yet I fail to do so. I have been able to identify the black hole issue and the character disappearing.

I released a new version earlier today that updates the dependencies to the latest versions which somehow made it compatible with older skyline versions but other than that, I’m not sure at all on why you’re facing this issue. I can ask some people on the modding community to test the mod and see if they get a similar issue.

**Comment by MetalGearPearl** [comment] 2023-06-22 21:55
Of course, take your time
And if you need a file or something from my Smash tell me and I can send it to you

**Comment by NemesisSSBU** [comment] 2023-06-24 09:36
After some very extensive testing and updating files to the latest possible versions, I still haven't encountered Dracula crashing the game or WOL Master Hand spawning in as Mario. I have however found the issues with Marxs' blackhole, Dharkon and Galeem spawning in within training mode which have all been addressed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.8.4). But I apologize, I really cannot think of anything that could be causing this issue as I've looked deeply into the code and play tested on two different computers with Ryujinx and two modded Switches that haven't come up with the issues you've been experiencing.

I truly am stumped if you're fully updated to the most up-to-date versions of atmosphere, ARCropolis, Skyline, the mod, and have no conflicting code edit mods. My best bet would be to ask the Smash modding community on Discord for assistance with possible outdated files or some type of hidden confliction with the mod.

**Comment by MetalGearPearl** [comment] 2023-06-24 16:37
I see, thank you so much
So I'll keep seeing what could be

**Comment by NemesisSSBU** [comment] 2023-06-24 20:12
If you can, can I see a screenshot of what’s within your ARCropolis plugins folder (where lib.nro files are located)? There could be some hidden stuff that may be hard to see since a few times I somehow had duplicate files which caused similar issues to what you’re describing.

**Comment by MetalGearPearl** [comment] 2023-06-24 23:36
Of course, here's my plugin list
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/137255015/94fc27fd-62f7-4d72-acf1-7c175c640928)
And nope, I have .msbtx files, I have only one .msbt file

**Comment by NemesisSSBU** [comment] 2023-06-25 00:44
Hmm, I just tried playing with almost all those mods in that screen shot (except for edge_taunt, ice_climber_extend, silentmariovoice, and unlock_camera) and I didn't crash. Have you tried playing without any other mods at all installed except for this plugin then if that works start to slowly add in mods one by one until you find which mod creates the issue?

**Comment by MetalGearPearl** [comment] 2023-06-25 01:37
Well... I tried with only using your playable bosses mod and nothing changed, I deleted the other plugins you didn't tested but the problem persists, Galeem, Darkhon and Dracula crash the game and WoL Master Hand still appears as Mario ;(

**Comment by NemesisSSBU** [comment] 2023-06-25 02:43
Did you test even with the mods in your mod folder (not Arcropolis plugins) disabled?

**Comment by MetalGearPearl** [comment] 2023-06-25 02:46
I have no mods disabled, they are all enabled

**Comment by NemesisSSBU** [comment] 2023-06-25 02:49
Can you try only with the Bosses mod within the ultimate folder and only the libcomp_boss.nro file in the plugins folder?

**Comment by MetalGearPearl** [comment] 2023-06-25 19:47
I'll see what can I do, but i won't be home this week, so I'll try that when I come back

**Comment by NemesisSSBU** [comment] 2023-06-25 20:53
Of course! Take your time, no rush.

**Comment by NemesisSSBU** [comment] 2023-06-27 23:11
I was able to fully replicate the issue by having either a conflicting msg_name.msbt file or no msg_name.msbt file in my Bosses —> ui —> message folder and having a language other than English as your language for Smash. In order to fix this you need to either fix the conflicting msbt file (this conflict would be caused by having other mods with an msbt file or not having the msbt file in the Bosses mod folder at all) or you can set your main language in SSBU to English.

**Comment by NemesisSSBU** [comment] 2023-06-27 23:45
I added some multi-language support into the base libcomp_boss.nro file in the [latest build](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.9.2) but specifically with Spanish and no msg_name.msbt file installed, Dharkon, Galeem, and Dracula crash even without their mod loaded; their UI presence is simply bugged which unfortunately that's something on Nintendo's end. The only way to fix this would be, as stated before, to switch to English or somehow solve the conflicting msg_name.msbt files.

But some good news, WOL Master Hand should work regardless of the msg_name.msbt file.

**Comment by MetalGearPearl** [comment] 2023-06-28 14:37
Thanks a lot! Today I will return home, I will make the necessary adjustments today

**Comment by MetalGearPearl** [comment] 2023-06-29 19:45
Hi, everything worked!! Thanks a lot!!
Everything seems that the problem was a msbtx file and the game in Spanish, I changed it and everything works now

**Comment by MetalGearPearl** [comment] 2023-06-29 19:48
And by the way, is there any way to change the order of the headers in the CSS? Because I have the characters sorted by franchise and the bosses are among other fighters

**Comment by NemesisSSBU** [comment] 2023-06-29 22:44
Glad to hear it all works!

The way you would change the order of the character slots would be to open the lib.rs file in the src folder on this GitHub and recompile the entire mod after editing their specific slot number. It’s a bit of a process but it’s possible.

**Closed** 2023-06-29 23:50 UTC
Labels: bug
